services:
- type: web
  name: scrapingToolForHeroku
  runtime: python
  repo: https://github.com/ai2growth/scrapingToolForHeroku
  plan: standard
  buildCommand: |
    mkdir -p /opt/render/project/uploads
    mkdir -p /opt/render/project/downloads
    pip install -r requirements.txt
    flask db upgrade
  startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 run:app
  envVars:
  - key: PYTHON_VERSION
    value: 3.9.18
  - key: RENDER
    value: "true"
  - key: SCRAPEOPS_API_KEY
    value: "0139316f-c2f9-44ad-948c-f7a3439511c2"
  - key: UPLOAD_FOLDER
    value: /opt/render/project/uploads
  - key: DOWNLOADS_FOLDER
    value: /opt/render/project/downloads
  - key: DATABASE_URL
    fromDatabase:
      name: smartscrape-db
      property: connectionString
  - key: FLASK_APP
    value: run.py
  - key: SECRET_KEY
    generateValue: true
  region: oregon

databases:
  - name: smartscrape-db
    plan: standard
    region: oregon
    ipAllowList: []

version: "1"